  type Query {
    ping: String!
    me: User!
  }

  type Mutation {
    do_stuff: String!
  }

  type User {
    name: String!
  }

  type Subscription {
    pingCount: Int!
    infinite: Boolean!
  }